### ISSUE TITLE
Feature request: touch swipe

### ISSUE THREAD

**Issue by synw** [shhdgit/vue-easy-slider#12]
Hi, It would be great if the slider could work with the touch swipe event, so that it is suitable for phones where navigation with the arrows is less comfortable and natural.

**Comment by machinek56** [comment]
Hi, i cannot find this FR in master. Have you merged it?
I really need touch swipe support..

**Comment by shhdgit** [comment]
@machinek56 There's swipe support @3.2.0 when you import Slider and SliderItem from 'vue-easy-slider/dist/mobile'

**Comment by machinek56** [comment]
@shhdgit thanks, but i found that event *changeSlide* not fired when slide has changed.
I think you need update mobile functionality with latest changes master..

**Comment by shhdgit** [comment]
touch swipe is supported.
