### ISSUE TITLE
这个组件props带高度，报错

### ISSUE THREAD

**Issue by guguji5** [shhdgit/vue-easy-slider#17]
` <banner v-bind:height="336px"></banner>`
这么给轮播图赋值，会报错
(Emitted` value instead of an instance of Error) 
  Error compiling template:
```
<div>
    <banner v-bind:height="336px"></banner>
     <h1>{{ msg }}</h1>
  </div>
```
 - invalid expression: v-bind:height="336px"

刚了解vue，不太懂，望指教

**Comment by shhdgit** [comment]
@guguji5 你如果是v-bind:height="expression"的话，在expression里面得写js表达式。如果你要写336px应该写成v-bind:height="'336px'"。但是你这样写好像没什么意义的样子。html中直接写style="height: 336px"即可
