### ISSUE TITLE
This should be converted to vuejs plugin

### ISSUE THREAD

**Issue by mubaidr** [shhdgit/vue-easy-slider#24]
This can be, and i think, should be delivered as plugin of vuejs. 
This will allow easier integration through npm by just installing and importing. nothing to configure. 

I can work on it, will need some config files update and minor component changes. Let me know.

**Comment by shhdgit** [comment]
I agree with you. Plugin is a nice way to use this component.
But this is a break change. Maybe we can create a new branch named 4.0.0 and tag npm package as vue-easy-slider@plugin?

**Comment by mubaidr** [comment]
Yes, a new branch would be better. Btw i see master branch is not in use. We can use that too? While keeping the older versions in their respective branches.

**Comment by shhdgit** [comment]
Ok, let's use master branch.

**Comment by mubaidr** [comment]
Hi, I have an update. Please review master branch in my fork, major changes: 
- Added `editorconfig`, `eslint`
- Add webpack scripts for demo building, `docs` folder can be published through Github pages as demo/home page
- This plugin can be published to `npm` now. 
- Removed `slider-item`, use can construct slides inside `slider` component directly
- Removed animation component in favor of vuejs transitions (this needs to be discussed, we can either use vuejs transitions or custom implement using some dependency like velocityJs etc)
- Added demo/home page
- Add option to pause on hover
- API & styles are maintained as same
- [WIP] For direct  browser usage script bundle config is in progress

Demo: https://mubaidr.github.io/vue-easy-slider/
Complete list of commits: https://github.com/mubaidr/vue-easy-slider/commits/master

**Comment by shhdgit** [comment]
Sorry for the late reply.
I just published a @plugin version to npm. You can try to install plugin version through `npm i vue-easy-slider@plugin`.
But folder structure confuse me little bit. I want to adjust it later.

**Comment by mubaidr** [comment]
I believe there are two things needed to be done:

- Review author details, demo links etc in the project like package json, i might have missed something. 
- Plugin build script is not added (for direct usage in browser without npm)

Sure please adjust the folder accordingly. For now;
- demo: contains source for demo pages
- docs: contain the demo build
- src: contains plugin
- dist: (does not exists) Should contain built version of plugin

**Comment by shhdgit** [comment]
support now
