### ISSUE TITLE
No Types for TypeScript

### ISSUE THREAD

**Issue by crtjr64** [shhdgit/vue-easy-slider#39]
This is the message I get and I'm also new to Typescript but it appears that I need to have types for it to reference. I saw no such folder nor updates.

in [at-loader] ./ClientApp/components/home/homevue.ts:2:36 
    TS7016: Could not find a declaration file for module 'vue-easy-slider'. 'H:/Files/Projects/TunstallSoftwareCorpWebsite/TunstallSoftware/node_modules/vue-easy-slider/dist/index.js' implicitly has an 'any' type.
ERR

**Comment by shhdgit** [comment]
support.
