### ISSUE TITLE
Handle left or right keypress

### ISSUE THREAD

**Issue by haloboy777** [shhdgit/vue-easy-slider#40]
There should be a way to call next and prev functions to handle keypress pragmatically.

**Comment by Rozkalns** [comment]
Or it would be great if there would be exposed methods to trigger the next() or prev(), so we could implement this not only with the key press functionality, but also with hammer js swipes or something else.

**Edit:**
Actually, you can do this already.

In template:
```
<slider ref="slider">[...]</slider>
<button @click="next" v-hammer:swipe.right="next"></button>
```

In script:
```js
methods: {
  next () {
    this.$refs.slider.next()
  }
}
```
