### ISSUE TITLE
多图轮播重叠缺陷

### ISSUE THREAD

**Issue by ren-liang** [shhdgit/vue-easy-slider#44]
当应用存在多个路由页面时（轮播图属于其中一个路由页面），多个页面之间定时做自动路由切换      
var currentPath = this.$router.currentRoute.path;
      var routes = this.$router.options.routes;
      let pageCount = routes.length;
      //console.log(this.interval);
      if(this.interval == pageCount){
        //window.location.reload();
      }
      if(pageIndex >= routes.length) {
         pageIndex = 0;
      }
      this.interval++;
      this.$router.replace(routes[pageIndex++].path);
切换路由会出现首页的轮播图图片重叠的缺陷

**Comment by shhdgit** [comment]
感谢反馈

**Comment by shhdgit** [comment]
新版已修复
