### ISSUE TITLE
轮播会出现白屏

### ISSUE THREAD

**Issue by retronew** [shhdgit/vue-easy-slider#47]
官方给的demo可以复现改问题，当切换到其他页面并等待一段时间，再切回demo页的时候会出现一个延迟周期的白屏
![1](https://user-images.githubusercontent.com/7346148/49328778-ed5acc00-f5b0-11e8-988a-e28f01ee2d36.gif)

**Comment by shhdgit** [comment]
多谢反馈，正在重构中，这两天发个新版

**Comment by shhdgit** [comment]
新版已修复
