### ISSUE TITLE
Props indicators display error when 'false'

### ISSUE THREAD

**Issue by patrickmonteiro** [shhdgit/vue-easy-slider#51]
The props indicators are of type String, so when trying to set the Boolean value false it displays errors in the console because it waits for a String, even if it works.

Would not it be more interesting to use one 'props' for display and one for positioning?

**Comment by shhdgit** [comment]
Split two props is a good design, but I want keep props as few as possible. So I change prop type to [String, Boolean] @5.2.10.
Thanks for your help.

**Comment by patrickmonteiro** [comment]
@shhdgit Thanks for the quick response!
