### ISSUE TITLE
Start at a specific slide dynamically

### ISSUE THREAD

**Issue by bi6o** [shhdgit/vue-easy-slider#64]
First of all, thanks for this simple yet powerful tool, it is very useful and lightweight. I was wondering if there is a possibility to start the slider at a specific slide? Meaning, if my slides are static and always have specific indexes, would it be possible to start the slider sometimes at slide 1 and sometimes at slide 3 for example?

**Comment by shhdgit** [comment]
Maybe you can generate a random index when created?
