### ISSUE TITLE
'document not defined' error Nuxt 2.15

### ISSUE THREAD

**Issue by vinosamari** [shhdgit/vue-easy-slider#71]
I just installed the plugin and did the necessary config for plugins in Nuxt and got this 'document not defined' error on initial server load. Is there something i'm missing?

**Comment by vinosamari** [comment]
Figured it out! Nuxt SSR.
Solution: I wrapped it in a <client-only> tag. Works like a charm.
Great Plugin! @shhdgit

**Comment by Kurikania** [comment]
> Figured it out! Nuxt SSR. Solution: I wrapped it in a tag. Works like a charm. Great Plugin! @shhdgit

Please, could you be more specific. I am facing the same trouble

**Comment by vinosamari** [comment]
Sorry for the delayed response. use `<no-ssr> or <client-only>` tags to wrap around the slider component
