### ISSUE TITLE
切换路由时 控制台 重复报错 跟定时器的节奏一样

### ISSUE THREAD

**Issue by nettieJin** [shhdgit/vue-easy-slider#9]
我用到了 路由 然后采用webpack打包 当我从轮播页面切换到 别的页面的时候 会根据定时器的时间间隙 在控制台重复 报错 报错信息如下：
index.js?6abc:1 Uncaught TypeError: Cannot read property 'length' of null
    at eval (eval at <anonymous> (app.js:7042), <anonymous>:1:6138)

我猜是 当我切换路由时并没有 停止定时器的相关功能 请问怎么解决呀
我尝试用destroyed来销毁定时器 但获取不到需要销毁的 timer

**Comment by nettieJin** [comment]
代码如下：
<template>
	<slider width="1000px" animation="normal" :interval="5000" :speed="1000" :control-btn='false'>
	  <slider-item :style="{ backgroundColor: '#3f51b5' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	  <slider-item :style="{ backgroundColor: '#eee' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	  <slider-item :style="{ backgroundColor: '#f44336' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	</slider>
</template>
<script type="text/javascript">
	import { Slider, SliderItem } from 'vue-easy-slider'
	export default{
		components: {
			Slider,
			SliderItem
		},
		destroyed: function() {
			console.log('清除定时器？？？');
			// clearInterval(timer);
		}
	}
</script>

**Comment by nettieJin** [comment]
HTML:
	`<slider width="1000px" animation="normal" :interval="5000" :speed="1000" :control-btn='false'>`
	`  <slider-item :style="{ backgroundColor: '#3f51b5' }"><img></slider-item>`
	`  <slider-item :style="{ backgroundColor: '#eee' }"><img></slider-item>`
	`  <slider-item :style="{ backgroundColor: '#f44336' }"><img></slider-item>`
	`</slider>"`
JS:
	import { Slider, SliderItem } from 'vue-easy-slider'
	export default{
		components: {
			Slider,
			SliderItem
		},
		destroyed: function() {
			console.log('清除定时器');
			// clearInterval(timer);
		}
	}

**Comment by nettieJin** [comment]
<template>
	<slider width="1000px" animation="normal" :interval="5000" :speed="1000" :control-btn='false'>
	  <slider-item :style="{ backgroundColor: '#3f51b5' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	  <slider-item :style="{ backgroundColor: '#eee' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	  <slider-item :style="{ backgroundColor: '#f44336' }"><img src="../../../../static/images/find-play-exp.jpg"></slider-item>
	</slider>
</template>

**Comment by nettieJin** [comment]
<template>
	<slider width="1000px" animation="normal" :interval="5000" :speed="1000" :control-btn='false'>
	  <slider-item :style="{ backgroundColor: '#3f51b5' }"><img></slider-item>
	  <slider-item :style="{ backgroundColor: '#eee' }"><img></slider-item>
	  <slider-item :style="{ backgroundColor: '#f44336' }"><img></slider-item>
	</slider>
</template>

**Comment by shhdgit** [comment]
对，的确是定时器的问题，要在组件beforeDestory的时候清除一下定时器。感谢
抱歉回晚了。已修复
